name: Build EXE and Installers

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:

      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r install_root/requirements.txt

      # =============================
      # BUILD CON DATOS
      # =============================

      - name: Generar EXE CON datos
        run: |
          python -m PyInstaller --onedir --noconsole --clean --noconfirm --icon=./install_root/MovilidadESII.ico --name MovilidadESII_Demo launcher_system.py

      - name: Instalar Inno Setup
        run: choco install innosetup --yes

      - name: Crear instalador CON datos
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss

      # =============================
      # LIMPIAR DIST
      # =============================

      - name: Limpiar carpeta dist
        run: Remove-Item -Recurse -Force dist

      # =============================
      # BUILD SIN DATOS
      # =============================

      - name: Generar EXE SIN datos
        run: |
          python -m PyInstaller --onedir --noconsole --clean --noconfirm --icon=./install_root/MovilidadESII.ico --name MovilidadESII_Clean launcher_system_sindata.py

      - name: Crear instalador SIN datos
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer_sindata.iss

      # =============================
      # SUBIR ARTEFACTOS
      # =============================

      - name: Subir instaladores
        uses: actions/upload-artifact@v4
        with:
          name: Instaladores
          path: |
            Output\*.exe
